sudo: required
language: rust
rust:
- nightly
before_install:
  - gem install package_cloud
  - cargo install cargo-deb
  - rustup target add i686-unknown-linux-gnu
script:
- cargo deb --target=i686-unknown-linux-gnu
deploy:
  provider: packagecloud
  repository: lobsters-bridge
  username: dix
  dist: 'ubuntu/xenial'
  package_glob: '*.deb'
  token:
    secure: WigvL8+gPjI67nwsjog8b3FBaqEJr3bFeeL2ipLH3+5irqcqB1oNfmqYIdI6cEL1bViwMYR1Quwc0Z/BXLA8qL0PtuUxRpsAHjBH5vznhbEzweYW3ySKYIBzqEF0GwPIhTlin5dt/FHow1S5B+3xgd6V17FTuLtyvBig4BkYzd+b9fDiyosxcHW9X0Lgdyg5MuK57voYrvXdqYKqKqFHGh7aJ7aKUrUMEHT+rDVXXl7JdVHoIqZNizNVnVoV+AQdyybzC2p84wX+c01s/UXlDFyZuyNkNFy3x7Ea9C5s6cntTyT06oRggKAFlkTOATAU5TbhKnJ5VzVh0ocbQhPfdOivzmPLkqbQKmmL84kbIOGKW5Ms9ZYPpXyYvHUrLjnhu73rKMGtB55+FpRbl3Eb0CheN5kWVTceJBDyifAvPq2kB2OpXJoDta9bJbh+GMZs9NN0Us31hxB9If8u1YGhcfMwiPswo8gZPKB2HqZfU49CcFK2Ec1WYRnJnCF7xTlRfU44lWFjBU7OBQHe48wRlHV5XgAOVT7+pgy5uDh03JWJ9WMoTPliyWCJoMTzeMq6u4qV6WtKykl0ptY4OaqZ4oUdGH+yCPD3paHhcUl+kMMTmzfw59enuxMojUcfzzndoo3Irtxcczm34cgWbcYh2GUsDyWkvzwQnX7yjAC/qiM=
